---
services:
  terraform-exam:
    build: .
    container_name: terraform-practice-exam
    ports:
      - "4880:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
